-- AlterTable
ALTER TABLE "User" ADD COLUMN     "groupId" TEXT NOT NULL DEFAULT '1';

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
